### ISSUE TITLE
Mapping preview failing for some datasets

### ISSUE THREAD

**Issue by peterdesmet** [LifeWatchINBO/data-publication#56]
The following datasets cannot generate a mapping preview (tested for all datasets):

* [ ] http://dataset.inbo.be/florabank1-occurrences
* [x] http://dataset.inbo.be/testwat-occurrences
* [x] http://dataset.inbo.be/belgian-coccinellidae-inbo-occurrences
* [x] http://dataset.inbo.be/saltabel-occurrences
* [x] http://dataset.inbo.be/vis-inland-occurrences
* [x] http://dataset.inbo.be/watervogels-occurrences
* [x] http://dataset.inbo.be/broedvogel-atlas-occurrences
* [x] http://dataset.inbo.be/invasive-bullfrog-occurrences

This seems to fail any data publication (tested for broedvogels and watervogels).

It's hard to find a common issue between these datasets (e.g. most NBN datasets work, but not all). I talked with @kbraak about this and it might be related to `null` values in the SQL query. We should test if replacing them with empty strings resolves the issue.

**Comment by kbraak** [comment]
I have confirmed this is a bug related to ```null``` values in the SQL result set. Please see https://github.com/gbif/ipt/issues/1205 that includes a temporary work around.  I will make a new minor version of the IPT to this fix soon though.

**Comment by peterdesmet** [comment]
The mapping preview works again for all datasets, except florabank1: it doesn't fail there, but it takes forever to show the preview (I never saw it): probably due to the large number of records. Closing issue.
