### ISSUE TITLE
Link from Gbif  VIS summary page towards github repo broken

### ISSUE THREAD

**Issue by stijnvanhoey** [LifeWatchINBO/data-publication#72]
The description on the page http://www.gbif.org/dataset/823dc56e-f987-495c-98bf-43318719e30f  contains a link towards the vis-inland-occurrences repo, https://github.com/LifeWatchINBO/vis-inland-occurrences. 
However, probably this was moved earlier towards this repo, so the link should be https://github.com/LifeWatchINBO/data-publication/tree/master/datasets/vis-inland-occurrences instead of https://github.com/LifeWatchINBO/vis-inland-occurrences

**Comment by peterdesmet** [comment]
Thanks for reporting @stijnvanhoey. This has been corrected in the [metadata](https://github.com/LifeWatchINBO/data-publication/blob/master/datasets/vis-inland-occurrences/metadata.md) and is staged in the IPT, but I'm waiting to republish until the data has been corrected (see #33). The same is true for some other datasets.

Maybe I shouldn't wait and already republish the dataset with updated metadata...

**Comment by peterdesmet** [comment]
I have republished all 4 datasets for which I have reviewed and updated the metadata (but not yet the data). As a result, the GitHub link is now correct on the GBIF dataset page for vis-inland-occurrences: http://www.gbif.org/dataset/823dc56e-f987-495c-98bf-43318719e30f
