### ISSUE TITLE
when taxonRank is not a taxon

### ISSUE THREAD

**Issue by DimEvil** [LifeWatchINBO/data-publication#86]
* `scientificName` is `Invasieve zomergans`    (functional group)
* `scientificName` is `Anser anser f. domesticus x Branta canadensis` or ...    (functional group)
* `scientificName` is `Anser anser forma domesticus`

**Comment by peterdesmet** [comment]
:question:

**Comment by peterdesmet** [comment]
This has been solved

**Comment by peterdesmet** [comment]
Decided to map `Invasieve zomergans` to `Anseridae` (family).
