### ISSUE TITLE
Number of records mismatch with GBIF

### ISSUE THREAD

**Issue by peterdesmet** [LifeWatchINBO/data-publication#90]
For the following datasets there is a mismatch between the number of occurrences at the source and the number of records displayed by GBIF. GBIF overestimates the number of occurrences, because it does not auto-delete occurrences removed from the DwC-A. This has been [suggested as a feature](http://dev.gbif.org/issues/browse/PF-2279). See also this [issue on Florabank](http://dev.gbif.org/issues/browse/POR-2343).

dataset | version | dwc-a | gbif
--- | --- | --- | ---
http://dataset.inbo.be/florabank1-occurrences | 45.3 | 3,660,135 | 3,661,250
http://dataset.inbo.be/vis-inland-occurrences | 9.3 | 365,065 | 365,608
http://dataset.inbo.be/vis-estuarine-occurrences | 9.3 | 51,181 | 59,078
http://dataset.inbo.be/watervogels-occurrences | 3.3 | 601,495 | 605,228

**Comment by peterdesmet** [comment]
Suggested auto-delete: http://dev.gbif.org/issues/browse/PF-2279

**Comment by timrobertson100** [comment]
Thank you for the feature request.  I have fixed the 3 smallest ones, but the larger one seems to have discrepancies.  I am forcing a recrawl now.

If there is a web developer who cares to try, it would be relatively easy to fork this project [1] to use the IPT inventory [2] to automate this check.

[1] http://timrobertson100.github.io/vertnet-gbif-diagnostic/target/index.html
[2] http://data.inbo.be/ipt/inventory/dataset

**Comment by timrobertson100** [comment]
All 4 datasets are now correctly up to date in GBIF

**Comment by peterdesmet** [comment]
Thanks @timrobertson100
