### ISSUE TITLE
Rename summering geese dataset

### ISSUE THREAD

**Issue by peterdesmet** [LifeWatchINBO/data-publication#92]
`invasive-geese-occurrences` is incorrect, as the dataset includes counts of all summering geese, not only invasive ones. New shortname is `zomerganzen-occurrences`

Update:

* [x] GitHub dataset
* [x] GitHub label
* [x] Google spreadsheet
* [x] Google drive

**Comment by peterdesmet** [comment]
@DimEvil, since we'll publish this as an sampling event dataset, we should also use a new shortname extension (not `-occurrences`).

How GBIF names those:

* Occurrence core -> Occurrence dataset
* Taxon core -> Checklist dataset
* Event core -> Sampling event dataset (e.g. http://www.gbif.org/dataset/78360224-5493-45fd-a9a0-c336557f09c3)

We currently already have `-occurrences` and `-checklist`. What do we use?

```
-sampling-events
-sampling
-events
...
```

**Comment by DimEvil** [comment]
-events

**Comment by peterdesmet** [comment]
OK, `zomerganzen-events`

**Comment by DimEvil** [comment]
very OK, `zomerganzen-events`
