### ISSUE TITLE
Add absent occurrences to 13 empty events

### ISSUE THREAD

**Issue by peterdesmet** [LifeWatchINBO/data-publication#98]
13 of the 3730 events in zomerganzen have no associated occurrences, while we typically record "nultellingen" as `individualCount=0, occurrenceStatus=absent`. In fact, the bulk of the occurrences (15406) are of that type.

According to @timadriaens, those are Egyptian goose catches in West-Flanders. We'll have to check in Recorder why the observations are missing.

/cc @SanderDevisscher

**Comment by peterdesmet** [comment]
The 13 records: [empty-events.txt](https://github.com/LifeWatchINBO/data-publication/files/100686/empty-events.txt)

**Comment by timadriaens** [comment]
12 records are egyptian geese captures in west flanders, these could be either zeros lacking from the occurrence dataset (nothing captured), maybe something to do with batch import in recorder? The one record from the moult capture is also from western flanders (so probably Inagro capture). We should go back to the original field forms/excel sheets

**Comment by SanderDevisscher** [comment]
Die 13 geven in feite de datum en tijdbesteding voor het opzetten van de larson trap weer.
Aangezien er die dagen meestal geen dieren gezien of gevangen zijn hangen er geen occurences aan. Dit is echter niet altijd zo, in sommige gevallen werden er de eerste dag al ganzen gevangen en in het geval van andere werd de eerste dag niet gerapporteerd.   
Wat we hier het beste mee doen moet ik eens met tim overleggen. 
Opties zijn:
- Zo laten en in de metadata uitleggen
- Ander sample type uitvinden bvb "opzet larsen trap"
- Zero occurences toevoegen

**Comment by timadriaens** [comment]
Sander, can you look up the original forms/sheets for those 13 records? Inagro --> afvangst Stil Ende

**Comment by SanderDevisscher** [comment]
I'll look them up

**Comment by timadriaens** [comment]
maybe this one?

[overzicht afgevangen Nijlganzen west-vlaanderen 2014.xlsx](https://github.com/LifeWatchINBO/data-publication/files/100690/overzicht.afgevangen.Nijlganzen.west-vlaanderen.2014.xlsx)

**Comment by SanderDevisscher** [comment]
the events are from 2013

**Comment by timadriaens** [comment]
and this one

[globaal overzicht afvangsten_WVL voor INBO.xlsx](https://github.com/LifeWatchINBO/data-publication/files/100693/globaal.overzicht.afvangsten_WVL.voor.INBO.xlsx)

**Comment by timadriaens** [comment]
found the 2013 records i think

[resultaten vangkooi Luc.xlsx](https://github.com/LifeWatchINBO/data-publication/files/100696/resultaten.vangkooi.Luc.xlsx)

**Comment by SanderDevisscher** [comment]
this is the comment for the 2012 moult capture in brugge 

"Onvolledige rapportage "

**Comment by SanderDevisscher** [comment]
this is the file

[resultaten vangkooi Luc.xlsx](https://github.com/LifeWatchINBO/data-publication/files/100705/resultaten.vangkooi.Luc.xlsx)

**Comment by timadriaens** [comment]
same file...

**Comment by SanderDevisscher** [comment]
Mine contains more events

**Comment by SanderDevisscher** [comment]
I put it here back in the day
Q:\Projects\PRJ_RINSE\Activiteiten_WP3\demonstrations\geese\Data\Ruw

**Comment by timadriaens** [comment]
cannot find the 2012 moult capture in brugge

**Comment by SanderDevisscher** [comment]
probably a mail
will have a look at my archives if I can

**Comment by SanderDevisscher** [comment]
In 13 cases no geese were caught the first day
but since 1 of these capture periods resulted in no geese caught overall I made the period including the first day a zero occurance. The period in question is the 19th to 21st of april.

**Comment by SanderDevisscher** [comment]
What shall I do ?
- Leave as is?
- Add zero occurences ?
- Split the period?
- Invent a new sample type to indicate a setup day? (and split up the period)

**Comment by timadriaens** [comment]
best zero occurrence (nijlgans) van maken

**Comment by timadriaens** [comment]
going throuh the mails to find the 2012 capture in Bruges, if we cannot find it i suggest removal

**Comment by timadriaens** [comment]
gevonden denk ik, maar zonder rapportage

[zomerganzen 2012 (svz 21 september).xlsx](https://github.com/LifeWatchINBO/data-publication/files/100807/zomerganzen.2012.svz.21.september.xlsx)

**Comment by timadriaens** [comment]
resultaten wellicht op te vragen bij ANB (Thomas Debonnet?) was afvangst georganiseerd door stad Brugge. Stil Ende zat wel een grote groep Canadaganzen traditioneel

**Comment by SanderDevisscher** [comment]
dat is em

**Comment by timadriaens** [comment]
for now, we can leave the event as such, we can always add the data later when we have them

**Comment by timadriaens** [comment]
I guess having an event without an occurrence is actually not a problem

**Comment by peterdesmet** [comment]
No, not a problem. Should I close this issue? I'll republish the dataset with DOI now.

**Comment by SanderDevisscher** [comment]
Still working on the 12

**Comment by peterdesmet** [comment]
Ah OK, in that case I'll wait.

**Comment by SanderDevisscher** [comment]
Can you check if the 12 are solved ?

**Comment by peterdesmet** [comment]
In the production data, I now count 20415 occurrences (11 more than 20404). 2 events have no occurrences still:

BFN00179000024TT: Invexo, 2012
BFN0017900002QVV: Rinse, 2013-04-17

Can you verify if this is OK?

**Comment by SanderDevisscher** [comment]
The event in RINSE (17/04/2013) should have 2 occurences; 1, Adult Man, (Exact) and 1, Adult Vrouw, (Exact) according to recorder
The event in INVEXO is just missing the occurence data.

**Comment by SanderDevisscher** [comment]
And that can be considered correct

**Comment by peterdesmet** [comment]
The RINSE record is not included because "failed pending verification". Do you want to update this before publication or leave it as it is?

**Comment by SanderDevisscher** [comment]
Should be ok for publication now

**Comment by peterdesmet** [comment]
Thanks, version 1.1 is now published: http://dataset.inbo.be/zomerganzen-events
